### ISSUE TITLE
header中包含: 字符串无法正确解析

### ISSUE THREAD

**Issue by shenzh1990** [gotoeasy/glang#1]
req.Header.Set("Content-Type", "application/json;charset=UTF-8")
	for i, max := 0, len(headers); i < max; i++ {
		strs := Split(headers[i], ":")
		if len(strs) > 1 {
			req.Header.Set(Trim(strs[0]), Trim(strs[1]))
		}
	}
使用这个有一个缺陷，无法使用header中包含: 字符串，无法正确解析到header

**Comment by gotoeasy** [comment]
何以见得？

我调试下后看结果是正常
![image](https://github.com/gotoeasy/glang/assets/9602197/2068452d-ac8a-44ae-8c33-a23c076e4fcc)

**Comment by shenzh1990** [comment]
比如在header中设置一个时间参数  TIMESTAMP : 2024-05-31T06:06:09.627Z ,按照您的逻辑，实际请求的header中会变成
key                ：value
TIMESTAMP :  2024-05-31T06
06                 :  09.627Z

**Comment by shenzh1990** [comment]
在使用你的方法时，我需要新增一个比如时间类型的header，预期的结果是
timesstamp:2024-05-31T06:06:09.627Z
但是实际的结果是
timesstamp:2024-05-31T06
最后将header的类型改为map[string]string ，并使用去解决这个问题

**Comment by gotoeasy** [comment]
理解你的意思了，值含有半角冒号引起，已修复
![image](https://github.com/gotoeasy/glang/assets/9602197/1122f1d7-c800-4523-91bd-45100ad139dc)
